name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "NuGet package version (e.g. 1.2.3)"
        required: true
        type: string

jobs:
  build:
    name: Build, Test & Pack
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ inputs.version }}

  publish:
    name: Publish to NuGet
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download NuGet package artifact
        uses: actions/download-artifact@v8
        with:
          name: nupkg
          path: ./nupkg

      - name: NuGet login (OIDC)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
